name: Build
on: [push, pull_request]
jobs:
  build:
    name: >-
      ${{ matrix.os }} ruby ${{ matrix.ruby }} ${{ matrix.db }}
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.allow-failure || false }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
#          - windows-2022
#          - macos-latest
        ruby:
#          - 2.7
          - 3.0
#          - 3.1
#          - 3.2
#          - 3.3
#          - head
        mysql-version:
#          - mysql-8.0
          - mysql-5.7
          - mysql-5.6
#          - mariadb-10.11
#          - mariadb-10.6

      # On the fail-fast: true, it cancels all in-progress jobs
      # if any matrix job fails, which we don't want.
      fail-fast: false
    env:
      BUNDLE_WITHOUT: development
      # reduce MacOS CI time, don't need to clean a runtime that isn't saved
      HOMEBREW_NO_INSTALL_CLEANUP: 1
      HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK: 1
    steps:
      - uses: actions/checkout@v4
      - uses: shogo82148/actions-setup-mysql@v1
        with:
          mysql-version: ${{ matrix.mysql-version }}
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - run: bundle exec rake spec -- $rake_spec_opts
